/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frames;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author manue
 */
public class PanelPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form PanelPrincipal
     */
    public PanelPrincipal() {
        setOpaque(false);
        
        initComponents();
                setOpaque(false);

        Usuario.setBounds(200, 300, 250, 40);
        Btn1.setOpaque(false);
        Btn1.setBorder(null);
        Btn1.setBackground(new Color(0, 150, 136, 80));
        Texto1.setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 0, 0, 0));
        Texto2.setBorder(javax.swing.BorderFactory.createEmptyBorder(120, 0, 0, 0));
        Texto3.setBorder(javax.swing.BorderFactory.createEmptyBorder(120, 0, 0, 0));
        Texto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto1.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        Texto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto2.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        Texto3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto3.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        Usuario.setBackground(new Color(0, 150, 136, 80));
        Contrasena.setBackground(new Color(0, 150, 136, 80));
        BtnSesion.setBackground(new Color(0, 150, 136, 80));
        BtnRegistro.setBackground(new Color(0, 150, 136, 80));
;

    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Texto1 = new javax.swing.JLabel();
        Btn1 = new javax.swing.JTextField();
        Texto2 = new javax.swing.JLabel();
        Texto3 = new javax.swing.JLabel();
        Contrasena = new javax.swing.JPasswordField();
        Usuario = new javax.swing.JTextField();
        BtnSesion = new javax.swing.JButton();
        BtnRegistro = new javax.swing.JButton();

        Texto1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Texto1.setText("Bienvenido al Sistemas De Citas");

        Btn1.setBackground(new java.awt.Color(203, 241, 246));
        Btn1.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        Btn1.setText("Clinica dental Enriquez");
        Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn1ActionPerformed(evt);
            }
        });

        Texto2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Texto2.setText("Usuario");

        Texto3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Texto3.setText("Contraseña");

        Contrasena.setText("jPasswordField1");

        Usuario.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });

        BtnSesion.setText("Iniciar Sesion");
        BtnSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSesionActionPerformed(evt);
            }
        });

        BtnRegistro.setText("Registrarse");
        BtnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Btn1)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(Texto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Texto2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Texto3, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(937, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Texto1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Texto2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Texto3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(BtnSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(BtnRegistro)
                .addGap(83, 83, 83))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistroActionPerformed
        // TODO add your handling code here:
          JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);

    PanelFondo fondo = new PanelFondo();
    fondo.setLayout(new BorderLayout());

    fondo.add(new PanelRegistro(), BorderLayout.CENTER);

    frame.setContentPane(fondo);
    frame.revalidate();
    frame.repaint();
    }//GEN-LAST:event_BtnRegistroActionPerformed

    private void Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn1ActionPerformed

    private void BtnSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSesionActionPerformed
        // TODO add your handling code here:
            JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);

    PanelFondo fondo = new PanelFondo();
    fondo.setLayout(new BorderLayout());

    fondo.add(new PanelMenu(), BorderLayout.CENTER);

    frame.setContentPane(fondo);
    frame.revalidate();
    frame.repaint();
    }//GEN-LAST:event_BtnSesionActionPerformed

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Btn1;
    private javax.swing.JButton BtnRegistro;
    private javax.swing.JButton BtnSesion;
    private javax.swing.JPasswordField Contrasena;
    private javax.swing.JLabel Texto1;
    private javax.swing.JLabel Texto2;
    private javax.swing.JLabel Texto3;
    private javax.swing.JTextField Usuario;
    // End of variables declaration//GEN-END:variables
}
